alpha = [1, 2, 3, 4, 7,3,3]
beta = ['a', 'b', 'c', 'd']
print(beta[2])
alpha.append(9)
print(alpha)
#alpha.extend(beta)
#print(alpha)
#print(beta)
alpha.pop(0)
print(alpha)
print(len(alpha))
print(max(alpha))
print(min(alpha))
print(sum(alpha))
print(alpha.index(3))
alpha.reverse()
print(alpha)
alpha.sort()
print(alpha)